version: '3.8'

services:
  NodeGateway:
    build: ./NodeGateway
    env_file:
      - .env
    ports:
      - "3000:3000"

  FlaskCV:
    build: ./FlaskCV
    ports:
      - "5000:5000"

  FlutterApp:
    build: ./FlutterApp
    ports:
      - "8080:80"
